# Generated by Django 4.1.5 on 2023-01-17 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DealerCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("staff", models.PositiveBigIntegerField(verbose_name="Сотрудники")),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Завод"),
                            (1, "Дистрибьютор"),
                            (2, "Дилерский центр"),
                            (3, "Розничная сеть"),
                            (4, "Индивидуальный предприниматель"),
                        ],
                        default=2,
                        verbose_name="Статус в иерархии поставок",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("street", models.CharField(max_length=30)),
                ("build", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Название")),
                ("model", models.CharField(max_length=30, verbose_name="Модель")),
                (
                    "release_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата релиза"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RetailNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("staff", models.PositiveBigIntegerField(verbose_name="Сотрудники")),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Завод"),
                            (1, "Дистрибьютор"),
                            (2, "Дилерский центр"),
                            (3, "Розничная сеть"),
                            (4, "Индивидуальный предприниматель"),
                        ],
                        default=3,
                        verbose_name="Статус в иерархии поставок",
                    ),
                ),
                (
                    "contacts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics_sales_network.info",
                        verbose_name="Контактная информация",
                    ),
                ),
                (
                    "produce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics_sales_network.product",
                        verbose_name="Продукция",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics_sales_network.dealercenter",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="info",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="electronics_sales_network.location",
            ),
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Название")),
                ("staff", models.PositiveBigIntegerField(verbose_name="Сотрудники")),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Завод"),
                            (1, "Дистрибьютор"),
                            (2, "Дилерский центр"),
                            (3, "Розничная сеть"),
                            (4, "Индивидуальный предприниматель"),
                        ],
                        default=0,
                        verbose_name="Статус в иерархии поставок",
                    ),
                ),
                (
                    "contacts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics_sales_network.info",
                        verbose_name="Контактная информация",
                    ),
                ),
                (
                    "produce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics_sales_network.product",
                        verbose_name="Продукция",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entrepreneur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("staff", models.PositiveBigIntegerField(verbose_name="Сотрудники")),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Завод"),
                            (1, "Дистрибьютор"),
                            (2, "Дилерский центр"),
                            (3, "Розничная сеть"),
                            (4, "Индивидуальный предприниматель"),
                        ],
                        default=4,
                        verbose_name="Статус в иерархии поставок",
                    ),
                ),
                (
                    "contacts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics_sales_network.info",
                        verbose_name="Контактная информация",
                    ),
                ),
                (
                    "produce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics_sales_network.product",
                        verbose_name="Продукция",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics_sales_network.retailnetwork",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Distributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("staff", models.PositiveBigIntegerField(verbose_name="Сотрудники")),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Завод"),
                            (1, "Дистрибьютор"),
                            (2, "Дилерский центр"),
                            (3, "Розничная сеть"),
                            (4, "Индивидуальный предприниматель"),
                        ],
                        default=1,
                        verbose_name="Статус в иерархии поставок",
                    ),
                ),
                (
                    "contacts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics_sales_network.info",
                        verbose_name="Контактная информация",
                    ),
                ),
                (
                    "produce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics_sales_network.product",
                        verbose_name="Продукция",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics_sales_network.factory",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dealercenter",
            name="contacts",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="electronics_sales_network.info",
                verbose_name="Контактная информация",
            ),
        ),
        migrations.AddField(
            model_name="dealercenter",
            name="produce",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="electronics_sales_network.product",
                verbose_name="Продукция",
            ),
        ),
        migrations.AddField(
            model_name="dealercenter",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="electronics_sales_network.distributor",
                verbose_name="Поставщик",
            ),
        ),
    ]
